### ISSUE TITLE
Getting "Axios error" and unable to interface with Tapo P110

### ISSUE THREAD

**Issue by Sod-Almighty** [sanlike0911/node-red-contrib-tplink-tapo-connect-api#42]
I'm trying to control a P110 from NodeRed. I've configured the Tapo node with my TP-Link credentials, but no matter what I do, I continually get this response:

```
msg.payload : Object
  result: false
  errorInf: object
    message: "Axios error"
    error_code: 1
    agent: "AxiosError"
```

I've looked around in NodeRed for any additional logs I could give you, but did not find any.

**Comment by Sod-Almighty** [comment]
Well? Is anyone actually receiving these bug reports, or is the project dead?

**Comment by Sod-Almighty** [comment]
Yeah, that could be it. I try not to update firmware on my devices until I need to, because usually the new firmware breaks stuff, removes functionality or breaks compatibility with......well, _things like this._

Currently it says "1.2.3 Build 230425 Rel. 142542".

I have the option to update to "1.3.4 Build 250403 Rel. 150504". Should I go ahead?

**Comment by Sod-Almighty** [comment]
I'm afraid it's made no difference at all. I'm still getting an auth error:

> Error: Failed to authenticate with device 10.0.1.108 after 2 attempts. KLAP: KLAP handshake1 failed: timeout of 15000ms exceeded, Secure Passthrough: Authentication failed: TapoError: HTTP request failed: AxiosError: timeout of 10000ms exceeded"

I'm getting the same problem with another identical P110 as well. Both units work correctly via the iPhone app.

Are there any more logs or debugging steps I can take to help figure this out?

**Comment by sanlike0911** [comment]
Hi Sod-Almighty,

I apologize for the continued authentication errors you're experiencing. To resolve this issue, I will purchase a P110 and debug the problem.

Please answer the following questions.
- Is your device a P110M or a P110?
- Which country do you live in? The authentication region might be a factor.

Thank you for your cooperation.

sanlike0911.

**Comment by Sod-Almighty** [comment]
How do I get the logs? I don't know how to run these things from the console. I'm running NodeRED in a Docker instance.

**Comment by Sod-Almighty** [comment]
Thank you. But unfortunately, `0.5.2a` seems to be broken somehow:

1. It refuses to let me deploy the flow, complaining about "missing node types".
2. It is offering an upgrade from `0.5.2a` to `0.5.2-a`, which makes no sense.
3. Attempting to perform the upgrade from `0.5.2a` to 0.5.2-a has no effect.

<img width="572" height="601" alt="Image" src="https://github.com/user-attachments/assets/4823d6a6-49e5-42a5-a6b3-6f8f7aa3a614" />

**Comment by sanlike0911** [comment]
Hi Sod-Almighty,

It's possible that the issue is due to the node not being properly updated. Could you please try uninstalling the old node and then reinstalling it?

Thanks,

sanlike0911.

**Comment by Sod-Almighty** [comment]
Nope, there's definitely something wrong here. I spun up the latest NodeRED docker (4.1.0) and the problem remains.

**Comment by sanlike0911** [comment]
Could you please send me your node-red console logs?

**Comment by Sod-Almighty** [comment]
```
30 Jul 13:37:46 - [info]

Welcome to Node-RED
===================

30 Jul 13:37:46 - [info] Node-RED version: v4.1.0
30 Jul 13:37:46 - [info] Node.js  version: v20.19.4
30 Jul 13:37:46 - [info] Linux 6.2.16-3-pve x64 LE
30 Jul 13:37:46 - [info] Loading palette nodes
30 Jul 13:37:47 - [warn] ------------------------------------------------------
30 Jul 13:37:47 - [warn] [node-red-contrib-tplink-tapo-connect-api/tplink_command] Error: Cannot find module './tplink-tapo-connect/src/wrapper/tplink-tapo-connect-wrapper'
Require stack:
- /data/node_modules/node-red-contrib-tplink-tapo-connect-api/nodes/tplink_command.js
- /usr/src/node-red/node_modules/@node-red/registry/lib/loader.js
- /usr/src/node-red/node_modules/@node-red/registry/lib/index.js
- /usr/src/node-red/node_modules/@node-red/runtime/lib/nodes/index.js
- /usr/src/node-red/node_modules/@node-red/runtime/lib/index.js
- /usr/src/node-red/node_modules/node-red/lib/red.js
- /usr/src/node-red/node_modules/node-red/red.js
30 Jul 13:37:47 - [warn] [node-red-contrib-tplink-tapo-connect-api/tplink_brightness] Error: Cannot find module './tplink-tapo-connect/src/wrapper/tplink-tapo-connect-wrapper'
Require stack:
- /data/node_modules/node-red-contrib-tplink-tapo-connect-api/nodes/tplink_brightness.js
- /usr/src/node-red/node_modules/@node-red/registry/lib/loader.js
- /usr/src/node-red/node_modules/@node-red/registry/lib/index.js
- /usr/src/node-red/node_modules/@node-red/runtime/lib/nodes/index.js
- /usr/src/node-red/node_modules/@node-red/runtime/lib/index.js
- /usr/src/node-red/node_modules/node-red/lib/red.js
- /usr/src/node-red/node_modules/node-red/red.js
30 Jul 13:37:47 - [warn] [node-red-contrib-tplink-tapo-connect-api/tplink_colour] Error: Cannot find module './tplink-tapo-connect/src/wrapper/tplink-tapo-connect-wrapper'
Require stack:
- /data/node_modules/node-red-contrib-tplink-tapo-connect-api/nodes/tplink_colour.js
- /usr/src/node-red/node_modules/@node-red/registry/lib/loader.js
- /usr/src/node-red/node_modules/@node-red/registry/lib/index.js
- /usr/src/node-red/node_modules/@node-red/runtime/lib/nodes/index.js
- /usr/src/node-red/node_modules/@node-red/runtime/lib/index.js
- /usr/src/node-red/node_modules/node-red/lib/red.js
- /usr/src/node-red/node_modules/node-red/red.js
30 Jul 13:37:47 - [warn] [node-red-contrib-tplink-tapo-connect-api/tplink_status] Error: Cannot find module './tplink-tapo-connect/src/wrapper/tplink-tapo-connect-wrapper'
Require stack:
- /data/node_modules/node-red-contrib-tplink-tapo-connect-api/nodes/tplink_status.js
- /usr/src/node-red/node_modules/@node-red/registry/lib/loader.js
- /usr/src/node-red/node_modules/@node-red/registry/lib/index.js
- /usr/src/node-red/node_modules/@node-red/runtime/lib/nodes/index.js
- /usr/src/node-red/node_modules/@node-red/runtime/lib/index.js
- /usr/src/node-red/node_modules/node-red/lib/red.js
- /usr/src/node-red/node_modules/node-red/red.js
30 Jul 13:37:47 - [warn] [node-red-contrib-tplink-tapo-connect-api/tplink_toggle] Error: Cannot find module './tplink-tapo-connect/src/wrapper/tplink-tapo-connect-wrapper'
Require stack:
- /data/node_modules/node-red-contrib-tplink-tapo-connect-api/nodes/tplink_toggle.js
- /usr/src/node-red/node_modules/@node-red/registry/lib/loader.js
- /usr/src/node-red/node_modules/@node-red/registry/lib/index.js
- /usr/src/node-red/node_modules/@node-red/runtime/lib/nodes/index.js
- /usr/src/node-red/node_modules/@node-red/runtime/lib/index.js
- /usr/src/node-red/node_modules/node-red/lib/red.js
- /usr/src/node-red/node_modules/node-red/red.js
30 Jul 13:37:47 - [warn] [node-red-contrib-tplink-tapo-connect-api/tplink_turn_off] Error: Cannot find module './tplink-tapo-connect/src/wrapper/tplink-tapo-connect-wrapper'
Require stack:
- /data/node_modules/node-red-contrib-tplink-tapo-connect-api/nodes/tplink_turn_off.js
- /usr/src/node-red/node_modules/@node-red/registry/lib/loader.js
- /usr/src/node-red/node_modules/@node-red/registry/lib/index.js
- /usr/src/node-red/node_modules/@node-red/runtime/lib/nodes/index.js
- /usr/src/node-red/node_modules/@node-red/runtime/lib/index.js
- /usr/src/node-red/node_modules/node-red/lib/red.js
- /usr/src/node-red/node_modules/node-red/red.js
30 Jul 13:37:47 - [warn] [node-red-contrib-tplink-tapo-connect-api/tplink_turn_on] Error: Cannot find module './tplink-tapo-connect/src/wrapper/tplink-tapo-connect-wrapper'
Require stack:
- /data/node_modules/node-red-contrib-tplink-tapo-connect-api/nodes/tplink_turn_on.js
- /usr/src/node-red/node_modules/@node-red/registry/lib/loader.js
- /usr/src/node-red/node_modules/@node-red/registry/lib/index.js
- /usr/src/node-red/node_modules/@node-red/runtime/lib/nodes/index.js
- /usr/src/node-red/node_modules/@node-red/runtime/lib/index.js
- /usr/src/node-red/node_modules/node-red/lib/red.js
- /usr/src/node-red/node_modules/node-red/red.js
30 Jul 13:37:47 - [warn] ------------------------------------------------------
30 Jul 13:37:47 - [info] Settings file  : /data/settings.js
30 Jul 13:37:47 - [info] Context store  : 'default' [module=memory]
30 Jul 13:37:47 - [info] User directory : /data
30 Jul 13:37:47 - [warn] Projects disabled : editorTheme.projects.enabled=false
30 Jul 13:37:47 - [info] Flows file     : /data/flows.json
30 Jul 13:37:47 - [info] Server now running at http://127.0.0.1:1880/
30 Jul 13:37:47 - [info] Starting flows
30 Jul 13:37:47 - [info] [ui-base:My Dashboard] Node-RED Dashboard 2.0 (v1.26.0) started at /dashboard
30 Jul 13:37:47 - [info] [ui-base:My Dashboard] Created socket.io server bound to Node-RED port at path /dashboard/socket.io
30 Jul 13:37:47 - [info] Started flows
30 Jul 13:37:47 - [info] [mqtt-broker:Local mqtt broker] Connected to broker: mqtt://inferno:1883
30 Jul 13:38:36 - [info] Uninstalling module: node-red-contrib-tplink-tapo-connect-api
30 Jul 13:38:37 - [info] Uninstalled module: node-red-contrib-tplink-tapo-connect-api
30 Jul 13:38:37 - [info] Removed node types:
30 Jul 13:38:37 - [info]  - node-red-contrib-tplink-tapo-connect-api:tplink_tapo_connect_api
30 Jul 13:38:37 - [info]  - node-red-contrib-tplink-tapo-connect-api:tplink_command
30 Jul 13:38:37 - [info]  - node-red-contrib-tplink-tapo-connect-api:tplink_brightness
30 Jul 13:38:37 - [info]  - node-red-contrib-tplink-tapo-connect-api:tplink_colour
30 Jul 13:38:37 - [info]  - node-red-contrib-tplink-tapo-connect-api:tplink_status
30 Jul 13:38:37 - [info]  - node-red-contrib-tplink-tapo-connect-api:tplink_toggle
30 Jul 13:38:37 - [info]  - node-red-contrib-tplink-tapo-connect-api:tplink_turn_off
30 Jul 13:38:37 - [info]  - node-red-contrib-tplink-tapo-connect-api:tplink_turn_on
30 Jul 13:38:37 - [info] Removed plugins:
30 Jul 13:38:45 - [info] Installing module: node-red-contrib-tplink-tapo-connect-api, version: 0.5.2-a
30 Jul 13:38:50 - [info] Installed module: node-red-contrib-tplink-tapo-connect-api
30 Jul 13:38:50 - [info] Added node types:
30 Jul 13:38:50 - [info]  - node-red-contrib-tplink-tapo-connect-api:tplink_tapo_connect_api
30 Jul 13:38:50 - [info]  - node-red-contrib-tplink-tapo-connect-api:tplink_command : Error: Cannot find module './tplink-tapo-connect/src/wrapper/tplink-tapo-connect-wrapper'
Require stack:
- /data/node_modules/node-red-contrib-tplink-tapo-connect-api/nodes/tplink_command.js
- /usr/src/node-red/node_modules/@node-red/registry/lib/loader.js
- /usr/src/node-red/node_modules/@node-red/registry/lib/index.js
- /usr/src/node-red/node_modules/@node-red/runtime/lib/nodes/index.js
- /usr/src/node-red/node_modules/@node-red/runtime/lib/index.js
- /usr/src/node-red/node_modules/node-red/lib/red.js
- /usr/src/node-red/node_modules/node-red/red.js
30 Jul 13:38:50 - [info]  - node-red-contrib-tplink-tapo-connect-api:tplink_brightness : Error: Cannot find module './tplink-tapo-connect/src/wrapper/tplink-tapo-connect-wrapper'
Require stack:
- /data/node_modules/node-red-contrib-tplink-tapo-connect-api/nodes/tplink_brightness.js
- /usr/src/node-red/node_modules/@node-red/registry/lib/loader.js
- /usr/src/node-red/node_modules/@node-red/registry/lib/index.js
- /usr/src/node-red/node_modules/@node-red/runtime/lib/nodes/index.js
- /usr/src/node-red/node_modules/@node-red/runtime/lib/index.js
- /usr/src/node-red/node_modules/node-red/lib/red.js
- /usr/src/node-red/node_modules/node-red/red.js
30 Jul 13:38:50 - [info]  - node-red-contrib-tplink-tapo-connect-api:tplink_colour : Error: Cannot find module './tplink-tapo-connect/src/wrapper/tplink-tapo-connect-wrapper'
Require stack:
- /data/node_modules/node-red-contrib-tplink-tapo-connect-api/nodes/tplink_colour.js
- /usr/src/node-red/node_modules/@node-red/registry/lib/loader.js
- /usr/src/node-red/node_modules/@node-red/registry/lib/index.js
- /usr/src/node-red/node_modules/@node-red/runtime/lib/nodes/index.js
- /usr/src/node-red/node_modules/@node-red/runtime/lib/index.js
- /usr/src/node-red/node_modules/node-red/lib/red.js
- /usr/src/node-red/node_modules/node-red/red.js
30 Jul 13:38:50 - [info]  - node-red-contrib-tplink-tapo-connect-api:tplink_status : Error: Cannot find module './tplink-tapo-connect/src/wrapper/tplink-tapo-connect-wrapper'
Require stack:
- /data/node_modules/node-red-contrib-tplink-tapo-connect-api/nodes/tplink_status.js
- /usr/src/node-red/node_modules/@node-red/registry/lib/loader.js
- /usr/src/node-red/node_modules/@node-red/registry/lib/index.js
- /usr/src/node-red/node_modules/@node-red/runtime/lib/nodes/index.js
- /usr/src/node-red/node_modules/@node-red/runtime/lib/index.js
- /usr/src/node-red/node_modules/node-red/lib/red.js
- /usr/src/node-red/node_modules/node-red/red.js
30 Jul 13:38:50 - [info]  - node-red-contrib-tplink-tapo-connect-api:tplink_toggle : Error: Cannot find module './tplink-tapo-connect/src/wrapper/tplink-tapo-connect-wrapper'
Require stack:
- /data/node_modules/node-red-contrib-tplink-tapo-connect-api/nodes/tplink_toggle.js
- /usr/src/node-red/node_modules/@node-red/registry/lib/loader.js
- /usr/src/node-red/node_modules/@node-red/registry/lib/index.js
- /usr/src/node-red/node_modules/@node-red/runtime/lib/nodes/index.js
- /usr/src/node-red/node_modules/@node-red/runtime/lib/index.js
- /usr/src/node-red/node_modules/node-red/lib/red.js
- /usr/src/node-red/node_modules/node-red/red.js
30 Jul 13:38:50 - [info]  - node-red-contrib-tplink-tapo-connect-api:tplink_turn_off : Error: Cannot find module './tplink-tapo-connect/src/wrapper/tplink-tapo-connect-wrapper'
Require stack:
- /data/node_modules/node-red-contrib-tplink-tapo-connect-api/nodes/tplink_turn_off.js
- /usr/src/node-red/node_modules/@node-red/registry/lib/loader.js
- /usr/src/node-red/node_modules/@node-red/registry/lib/index.js
- /usr/src/node-red/node_modules/@node-red/runtime/lib/nodes/index.js
- /usr/src/node-red/node_modules/@node-red/runtime/lib/index.js
- /usr/src/node-red/node_modules/node-red/lib/red.js
- /usr/src/node-red/node_modules/node-red/red.js
30 Jul 13:38:50 - [info]  - node-red-contrib-tplink-tapo-connect-api:tplink_turn_on : Error: Cannot find module './tplink-tapo-connect/src/wrapper/tplink-tapo-connect-wrapper'
Require stack:
- /data/node_modules/node-red-contrib-tplink-tapo-connect-api/nodes/tplink_turn_on.js
- /usr/src/node-red/node_modules/@node-red/registry/lib/loader.js
- /usr/src/node-red/node_modules/@node-red/registry/lib/index.js
- /usr/src/node-red/node_modules/@node-red/runtime/lib/nodes/index.js
- /usr/src/node-red/node_modules/@node-red/runtime/lib/index.js
- /usr/src/node-red/node_modules/node-red/lib/red.js
- /usr/src/node-red/node_modules/node-red/red.js
30 Jul 13:39:25 - [info] Stopping flows
30 Jul 13:39:25 - [info] [mqtt-broker:Local mqtt broker] Disconnected from broker: mqtt://inferno:1883
30 Jul 13:39:25 - [info] Stopped flows
30 Jul 13:39:25 - [info] Updated flows
30 Jul 13:39:25 - [info] Waiting for missing types to be registered:
30 Jul 13:39:25 - [info]  - tplink_status
30 Jul 13:39:43 - [info] Stopping flows
30 Jul 13:39:43 - [info] Stopped flows
30 Jul 13:40:36 - [info]

Welcome to Node-RED
===================

30 Jul 13:40:36 - [info] Node-RED version: v4.1.0
30 Jul 13:40:36 - [info] Node.js  version: v20.19.4
30 Jul 13:40:36 - [info] Linux 6.2.16-3-pve x64 LE
30 Jul 13:40:36 - [info] Loading palette nodes
30 Jul 13:40:37 - [warn] ------------------------------------------------------
30 Jul 13:40:37 - [warn] [node-red-contrib-tplink-tapo-connect-api/tplink_command] Error: Cannot find module './tplink-tapo-connect/src/wrapper/tplink-tapo-connect-wrapper'
Require stack:
- /data/node_modules/node-red-contrib-tplink-tapo-connect-api/nodes/tplink_command.js
- /usr/src/node-red/node_modules/@node-red/registry/lib/loader.js
- /usr/src/node-red/node_modules/@node-red/registry/lib/index.js
- /usr/src/node-red/node_modules/@node-red/runtime/lib/nodes/index.js
- /usr/src/node-red/node_modules/@node-red/runtime/lib/index.js
- /usr/src/node-red/node_modules/node-red/lib/red.js
- /usr/src/node-red/node_modules/node-red/red.js
30 Jul 13:40:37 - [warn] [node-red-contrib-tplink-tapo-connect-api/tplink_brightness] Error: Cannot find module './tplink-tapo-connect/src/wrapper/tplink-tapo-connect-wrapper'
Require stack:
- /data/node_modules/node-red-contrib-tplink-tapo-connect-api/nodes/tplink_brightness.js
- /usr/src/node-red/node_modules/@node-red/registry/lib/loader.js
- /usr/src/node-red/node_modules/@node-red/registry/lib/index.js
- /usr/src/node-red/node_modules/@node-red/runtime/lib/nodes/index.js
- /usr/src/node-red/node_modules/@node-red/runtime/lib/index.js
- /usr/src/node-red/node_modules/node-red/lib/red.js
- /usr/src/node-red/node_modules/node-red/red.js
30 Jul 13:40:37 - [warn] [node-red-contrib-tplink-tapo-connect-api/tplink_colour] Error: Cannot find module './tplink-tapo-connect/src/wrapper/tplink-tapo-connect-wrapper'
Require stack:
- /data/node_modules/node-red-contrib-tplink-tapo-connect-api/nodes/tplink_colour.js
- /usr/src/node-red/node_modules/@node-red/registry/lib/loader.js
- /usr/src/node-red/node_modules/@node-red/registry/lib/index.js
- /usr/src/node-red/node_modules/@node-red/runtime/lib/nodes/index.js
- /usr/src/node-red/node_modules/@node-red/runtime/lib/index.js
- /usr/src/node-red/node_modules/node-red/lib/red.js
- /usr/src/node-red/node_modules/node-red/red.js
30 Jul 13:40:37 - [warn] [node-red-contrib-tplink-tapo-connect-api/tplink_status] Error: Cannot find module './tplink-tapo-connect/src/wrapper/tplink-tapo-connect-wrapper'
Require stack:
- /data/node_modules/node-red-contrib-tplink-tapo-connect-api/nodes/tplink_status.js
- /usr/src/node-red/node_modules/@node-red/registry/lib/loader.js
- /usr/src/node-red/node_modules/@node-red/registry/lib/index.js
- /usr/src/node-red/node_modules/@node-red/runtime/lib/nodes/index.js
- /usr/src/node-red/node_modules/@node-red/runtime/lib/index.js
- /usr/src/node-red/node_modules/node-red/lib/red.js
- /usr/src/node-red/node_modules/node-red/red.js
30 Jul 13:40:37 - [warn] [node-red-contrib-tplink-tapo-connect-api/tplink_toggle] Error: Cannot find module './tplink-tapo-connect/src/wrapper/tplink-tapo-connect-wrapper'
Require stack:
- /data/node_modules/node-red-contrib-tplink-tapo-connect-api/nodes/tplink_toggle.js
- /usr/src/node-red/node_modules/@node-red/registry/lib/loader.js
- /usr/src/node-red/node_modules/@node-red/registry/lib/index.js
- /usr/src/node-red/node_modules/@node-red/runtime/lib/nodes/index.js
- /usr/src/node-red/node_modules/@node-red/runtime/lib/index.js
- /usr/src/node-red/node_modules/node-red/lib/red.js
- /usr/src/node-red/node_modules/node-red/red.js
30 Jul 13:40:37 - [warn] [node-red-contrib-tplink-tapo-connect-api/tplink_turn_off] Error: Cannot find module './tplink-tapo-connect/src/wrapper/tplink-tapo-connect-wrapper'
Require stack:
- /data/node_modules/node-red-contrib-tplink-tapo-connect-api/nodes/tplink_turn_off.js
- /usr/src/node-red/node_modules/@node-red/registry/lib/loader.js
- /usr/src/node-red/node_modules/@node-red/registry/lib/index.js
- /usr/src/node-red/node_modules/@node-red/runtime/lib/nodes/index.js
- /usr/src/node-red/node_modules/@node-red/runtime/lib/index.js
- /usr/src/node-red/node_modules/node-red/lib/red.js
- /usr/src/node-red/node_modules/node-red/red.js
30 Jul 13:40:37 - [warn] [node-red-contrib-tplink-tapo-connect-api/tplink_turn_on] Error: Cannot find module './tplink-tapo-connect/src/wrapper/tplink-tapo-connect-wrapper'
Require stack:
- /data/node_modules/node-red-contrib-tplink-tapo-connect-api/nodes/tplink_turn_on.js
- /usr/src/node-red/node_modules/@node-red/registry/lib/loader.js
- /usr/src/node-red/node_modules/@node-red/registry/lib/index.js
- /usr/src/node-red/node_modules/@node-red/runtime/lib/nodes/index.js
- /usr/src/node-red/node_modules/@node-red/runtime/lib/index.js
- /usr/src/node-red/node_modules/node-red/lib/red.js
- /usr/src/node-red/node_modules/node-red/red.js
30 Jul 13:40:37 - [warn] ------------------------------------------------------
30 Jul 13:40:37 - [info] Settings file  : /data/settings.js
30 Jul 13:40:37 - [info] Context store  : 'default' [module=memory]
30 Jul 13:40:37 - [info] User directory : /data
30 Jul 13:40:37 - [warn] Projects disabled : editorTheme.projects.enabled=false
30 Jul 13:40:37 - [info] Flows file     : /data/flows.json
30 Jul 13:40:37 - [info] Server now running at http://127.0.0.1:1880/
30 Jul 13:40:37 - [info] Waiting for missing types to be registered:
30 Jul 13:40:37 - [info]  - tplink_status
30 Jul 13:40:59 - [info] Stopping flows
30 Jul 13:40:59 - [info] Stopped flows
30 Jul 14:12:20 - [info]

Welcome to Node-RED
===================

30 Jul 14:12:20 - [info] Node-RED version: v4.1.0
30 Jul 14:12:20 - [info] Node.js  version: v20.19.4
30 Jul 14:12:20 - [info] Linux 6.2.16-3-pve x64 LE
30 Jul 14:12:20 - [info] Loading palette nodes
30 Jul 14:12:21 - [warn] ------------------------------------------------------
30 Jul 14:12:21 - [warn] [node-red-contrib-tplink-tapo-connect-api/tplink_command] Error: Cannot find module './tplink-tapo-connect/src/wrapper/tplink-tapo-connect-wrapper'
Require stack:
- /data/node_modules/node-red-contrib-tplink-tapo-connect-api/nodes/tplink_command.js
- /usr/src/node-red/node_modules/@node-red/registry/lib/loader.js
- /usr/src/node-red/node_modules/@node-red/registry/lib/index.js
- /usr/src/node-red/node_modules/@node-red/runtime/lib/nodes/index.js
- /usr/src/node-red/node_modules/@node-red/runtime/lib/index.js
- /usr/src/node-red/node_modules/node-red/lib/red.js
- /usr/src/node-red/node_modules/node-red/red.js
30 Jul 14:12:21 - [warn] [node-red-contrib-tplink-tapo-connect-api/tplink_brightness] Error: Cannot find module './tplink-tapo-connect/src/wrapper/tplink-tapo-connect-wrapper'
Require stack:
- /data/node_modules/node-red-contrib-tplink-tapo-connect-api/nodes/tplink_brightness.js
- /usr/src/node-red/node_modules/@node-red/registry/lib/loader.js
- /usr/src/node-red/node_modules/@node-red/registry/lib/index.js
- /usr/src/node-red/node_modules/@node-red/runtime/lib/nodes/index.js
- /usr/src/node-red/node_modules/@node-red/runtime/lib/index.js
- /usr/src/node-red/node_modules/node-red/lib/red.js
- /usr/src/node-red/node_modules/node-red/red.js
30 Jul 14:12:21 - [warn] [node-red-contrib-tplink-tapo-connect-api/tplink_colour] Error: Cannot find module './tplink-tapo-connect/src/wrapper/tplink-tapo-connect-wrapper'
Require stack:
- /data/node_modules/node-red-contrib-tplink-tapo-connect-api/nodes/tplink_colour.js
- /usr/src/node-red/node_modules/@node-red/registry/lib/loader.js
- /usr/src/node-red/node_modules/@node-red/registry/lib/index.js
- /usr/src/node-red/node_modules/@node-red/runtime/lib/nodes/index.js
- /usr/src/node-red/node_modules/@node-red/runtime/lib/index.js
- /usr/src/node-red/node_modules/node-red/lib/red.js
- /usr/src/node-red/node_modules/node-red/red.js
30 Jul 14:12:21 - [warn] [node-red-contrib-tplink-tapo-connect-api/tplink_status] Error: Cannot find module './tplink-tapo-connect/src/wrapper/tplink-tapo-connect-wrapper'
Require stack:
- /data/node_modules/node-red-contrib-tplink-tapo-connect-api/nodes/tplink_status.js
- /usr/src/node-red/node_modules/@node-red/registry/lib/loader.js
- /usr/src/node-red/node_modules/@node-red/registry/lib/index.js
- /usr/src/node-red/node_modules/@node-red/runtime/lib/nodes/index.js
- /usr/src/node-red/node_modules/@node-red/runtime/lib/index.js
- /usr/src/node-red/node_modules/node-red/lib/red.js
- /usr/src/node-red/node_modules/node-red/red.js
30 Jul 14:12:21 - [warn] [node-red-contrib-tplink-tapo-connect-api/tplink_toggle] Error: Cannot find module './tplink-tapo-connect/src/wrapper/tplink-tapo-connect-wrapper'
Require stack:
- /data/node_modules/node-red-contrib-tplink-tapo-connect-api/nodes/tplink_toggle.js
- /usr/src/node-red/node_modules/@node-red/registry/lib/loader.js
- /usr/src/node-red/node_modules/@node-red/registry/lib/index.js
- /usr/src/node-red/node_modules/@node-red/runtime/lib/nodes/index.js
- /usr/src/node-red/node_modules/@node-red/runtime/lib/index.js
- /usr/src/node-red/node_modules/node-red/lib/red.js
- /usr/src/node-red/node_modules/node-red/red.js
30 Jul 14:12:21 - [warn] [node-red-contrib-tplink-tapo-connect-api/tplink_turn_off] Error: Cannot find module './tplink-tapo-connect/src/wrapper/tplink-tapo-connect-wrapper'
Require stack:
- /data/node_modules/node-red-contrib-tplink-tapo-connect-api/nodes/tplink_turn_off.js
- /usr/src/node-red/node_modules/@node-red/registry/lib/loader.js
- /usr/src/node-red/node_modules/@node-red/registry/lib/index.js
- /usr/src/node-red/node_modules/@node-red/runtime/lib/nodes/index.js
- /usr/src/node-red/node_modules/@node-red/runtime/lib/index.js
- /usr/src/node-red/node_modules/node-red/lib/red.js
- /usr/src/node-red/node_modules/node-red/red.js
30 Jul 14:12:21 - [warn] [node-red-contrib-tplink-tapo-connect-api/tplink_turn_on] Error: Cannot find module './tplink-tapo-connect/src/wrapper/tplink-tapo-connect-wrapper'
Require stack:
- /data/node_modules/node-red-contrib-tplink-tapo-connect-api/nodes/tplink_turn_on.js
- /usr/src/node-red/node_modules/@node-red/registry/lib/loader.js
- /usr/src/node-red/node_modules/@node-red/registry/lib/index.js
- /usr/src/node-red/node_modules/@node-red/runtime/lib/nodes/index.js
- /usr/src/node-red/node_modules/@node-red/runtime/lib/index.js
- /usr/src/node-red/node_modules/node-red/lib/red.js
- /usr/src/node-red/node_modules/node-red/red.js
30 Jul 14:12:21 - [warn] ------------------------------------------------------
30 Jul 14:12:21 - [info] Settings file  : /data/settings.js
30 Jul 14:12:21 - [info] Context store  : 'default' [module=memory]
30 Jul 14:12:21 - [info] User directory : /data
30 Jul 14:12:21 - [warn] Projects disabled : editorTheme.projects.enabled=false
30 Jul 14:12:21 - [info] Flows file     : /data/flows.json
30 Jul 14:12:21 - [info] Server now running at http://127.0.0.1:1880/
30 Jul 14:12:21 - [info] Waiting for missing types to be registered:
30 Jul 14:12:21 - [info]  - tplink_status
```

**Comment by sanlike0911** [comment]
I've found the cause of the problem. It seems the module path setting was incorrect in the new version I released. I will release a new version in a few hours. Please wait for it, as I will also release an experimental implementation for the EU version.

sanlike.

**Comment by Sod-Almighty** [comment]
The module path problem has been fixed, but I'm still getting no success controlling the P110.

> Error: Failed to authenticate with device 10.0.1.108 after 2 attempts. KLAP: KLAP authentication failed. V2: KLAP handshake1 failed: timeout of 15000ms exceeded; V1: KLAP V1 handshake failed: timeout of 15000ms exceeded, Secure Passthrough: Authentication failed: TapoError: HTTP request failed: AxiosError: timeout of 10000ms exceeded
    at GenericDeviceInfoRetriever.connect (/data/node_modules/node-red-contrib-tplink-tapo-connect-api/nodes/tplink-tapo-connect/devices/generic-device-info.js:73:15)
    at runNextTicks (node:internal/process/task_queues:60:5)
    at listOnTimeout (node:internal/timers:545:9)
    at process.processTimers (node:internal/timers:519:7)
    at async DeviceFactory.getDeviceInfo (/data/node_modules/node-red-contrib-tplink-tapo-connect-api/nodes/tplink-tapo-connect/factory/device-factory.js:33:13)
    at async operation (/data/node_modules/node-red-contrib-tplink-tapo-connect-api/nodes/tplink-tapo-connect/services/device-control-service.js:111:40)
    at async T...

**Comment by Sod-Almighty** [comment]
How are you getting on with the P110? Is there anything I can do to help with this?

**Comment by b1tnoise** [comment]
Hi, 
any update on the P110?  I also still have the AXXIOS error with my P110.
Thanks
Danny

**Comment by sanlike0911** [comment]
Hi Danny,

Thank you for your message.

Could you please let me know the firmware version of your P110?
If possible, could you also share the log file so that we can investigate the AXXIOS error more accurately?

Thank you again for your cooperation.
Best regards,

sanlike0911.

**Comment by sanlike0911** [comment]
Similar issues have been reported, and the following steps may resolve the problem:

In the Tapo app:
Go to Me > Third-Party Services, and ensure Third-Party Compatibility is turned on.

Switch it off, then back on again.

sanlike0911.

**Comment by b1tnoise** [comment]
Hi, I'll try it later, but the service was turned off indeed, need to check with NR :)

**Comment by VR1985** [comment]
Hi @sanlike0911,
I've just read trough this comment section and I'm experiencing the same issue like the other colleagues here --> Axios error.
It seems that this happend after the P110 update to firmwire release 1.4.0 Build 251020 Rel.161559
All of my 4pc P110 showing "all of a sudden" the same error.

I'm using the: https://flows.nodered.org/node/node-red-contrib-tplink-tapo-connect-api

the hint with the 3rd party in tapo app was already "on" all the time...

**Comment by Bro4dsword** [comment]
> Hi [@sanlike0911](https://github.com/sanlike0911), I've just read trough this comment section and I'm experiencing the same issue like the other colleagues here --> Axios error. It seems that this happend after the P110 update to firmwire release 1.4.0 Build 251020 Rel.161559 All of my 4pc P110 showing "all of a sudden" the same error.
> 
> I'm using the: https://flows.nodered.org/node/node-red-contrib-tplink-tapo-connect-api
> 
> the hint with the 3rd party in tapo app was already "on" all the time...

Hi,

I’m having the exact same issues with the same P110 models running the same firmware.
I’ve subscribed to the thread so hopefully an update soon! 🙏

Thanks.

**Comment by Bro4dsword** [comment]
Interestingly if I run a manual Inject on/off node into the Tapo on/off node it clears the Axios error and works.
🤷‍♂️

**Comment by Sod-Almighty** [comment]
> I’ve subscribed to the thread so hopefully an update soon! 🙏

Don't hold your breath. I reported this issue over a year ago and nothing has been achieved since.
